### ISSUE TITLE
what kind of test can we do?

### ISSUE THREAD

**Issue by 1cbyc** [uploadfly/uploadfly#5]
i am considering trying this or that but i do not know if this works the way i would...best!

**Comment by akinloluwami** [comment]
Idk what to reply with.

**Comment by 1cbyc** [comment]
send proof,,,,it is a test still
![Screenshot 2024-04-09 072552](https://github.com/uploadfly/uploadfly/assets/35623334/3a48ae68-9c2f-421f-a59d-5cfd024b13c9)
